// Auto-generated by Copilot per user prompt — review required
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_application_2/utils/booking_utils.dart';

void main() {
  test('inclusiveMonthsCount counts months inclusive', () {
    final a = DateTime(2023, 1, 1);
    final b = DateTime(2023, 3, 1);
    expect(inclusiveMonthsCount(a, b), 3);
  });

  test('applyGuestSurcharge rules', () {
    expect(applyGuestSurcharge(100000, 1), 100000);
    expect(applyGuestSurcharge(100000, 4), 150000);
    expect(applyGuestSurcharge(100000, 5), 200000);
  });

  test('calculateGrandTotal basic', () {
    final total = calculateGrandTotal(
      monthlyPrice: 2500000,
      months: 2,
      totalGuests: 2,
      discount: 0,
      fees: 10000,
    );
    expect(total, 2500000 * 2 + 10000);
  });
}
