// Auto-generated by Copilot per user prompt — manual review required
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class SavedProvider extends ChangeNotifier {
  static const _kKey = 'saved_room_ids';

  final Set<String> _saved = {};

  Set<String> get savedIds => Set.unmodifiable(_saved);

  bool isSaved(String id) => _saved.contains(id);

  Future<void> loadSaved() async {
    try {
      final sp = await SharedPreferences.getInstance();
      final raw = sp.getString(_kKey);
      if (raw == null || raw.isEmpty) return;
      final List<dynamic> list = jsonDecode(raw) as List<dynamic>;
      _saved.clear();
      for (final e in list) {
        _saved.add(e.toString());
      }
      notifyListeners();
    } catch (_) {
      // ignore errors but don't crash app
    }
  }

  Future<void> toggleSave(String id) async {
    try {
      if (_saved.contains(id)) {
        _saved.remove(id);
      } else {
        _saved.add(id);
      }
      // persist first, then notify listeners to ensure UI reads stable state
      final sp = await SharedPreferences.getInstance();
      await sp.setString(_kKey, jsonEncode(_saved.toList()));
      notifyListeners();
    } catch (_) {
      // ignore
    }
  }

  /// Backwards-compatible alias that some callers expect.
  Future<void> toggleSaved(String id) async => toggleSave(id);
}
