// Auto-generated by Copilot per user prompt — manual review required
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';

class MonthsSelection {
  final DateTime startDate;
  final DateTime endDate;
  final int monthsCount;

  MonthsSelection({
    required this.startDate,
    required this.endDate,
    required this.monthsCount,
  });
}

// Helpers
DateTime firstDayOfMonth(DateTime d) => DateTime(d.year, d.month, 1);
DateTime lastDayOfMonth(DateTime d) => DateTime(d.year, d.month + 1, 0);

int inclusiveMonthsCount(DateTime a, DateTime b) {
  final yearDiff = b.year - a.year;
  final monthDiff = b.month - a.month;
  return yearDiff * 12 + monthDiff + 1;
}

int monthsBetween(DateTime a, DateTime b) =>
    inclusiveMonthsCount(firstDayOfMonth(a), firstDayOfMonth(b));

Future<MonthsSelection?> showMonthPickerSheet(
  BuildContext context, {
  DateTime? initial,
}) {
  initial ??= DateTime.now();
  return showModalBottomSheet<MonthsSelection>(
    context: context,
    isScrollControlled: true,
    backgroundColor: Colors.transparent,
    builder: (ctx) {
      return _MonthPickerContent(initial: initial!);
    },
  );
}

class _MonthPickerContent extends StatefulWidget {
  final DateTime initial;

  const _MonthPickerContent({required this.initial});

  @override
  State<_MonthPickerContent> createState() => _MonthPickerContentState();
}

class _MonthPickerContentState extends State<_MonthPickerContent> {
  late DateTime _viewDate;
  DateTime? _firstSelected; // first month selected (day ignored)
  DateTime? _secondSelected;
  bool _didReturn = false;

  @override
  void initState() {
    super.initState();
    _viewDate = DateTime(widget.initial.year, widget.initial.month, 1);
  }

  void _prevMonth() {
    setState(
      () => _viewDate = DateTime(_viewDate.year, _viewDate.month - 1, 1),
    );
  }

  void _nextMonth() {
    setState(
      () => _viewDate = DateTime(_viewDate.year, _viewDate.month + 1, 1),
    );
  }

  void _onDayTap(DateTime day) {
    final chosen = DateTime(day.year, day.month, 1);
    setState(() {
      if (_firstSelected == null) {
        _firstSelected = chosen;
        _secondSelected = null;
      } else if (_firstSelected != null && _secondSelected == null) {
        if (chosen.isBefore(_firstSelected!)) {
          _secondSelected = _firstSelected;
          _firstSelected = chosen;
        } else {
          _secondSelected = chosen;
        }
      } else {
        // start new selection
        _firstSelected = chosen;
        _secondSelected = null;
      }
    });
  }

  bool _isMonthSelected(DateTime m) {
    if (_firstSelected == null) return false;
    final start = firstDayOfMonth(_firstSelected!);
    final end = firstDayOfMonth(_secondSelected ?? _firstSelected!);
    final fm = firstDayOfMonth(m);
    return !fm.isBefore(start) && !fm.isAfter(end);
  }

  @override
  Widget build(BuildContext context) {
    // build a simple month-by-month grid with days but tapping selects month.
    final formatter = DateFormat.yMMMM();
    return GestureDetector(
      onTap: () {},
      child: BackdropFilter(
        filter: ImageFilter.blur(sigmaX: 8, sigmaY: 8),
        child: DraggableScrollableSheet(
          initialChildSize: 0.6,
          minChildSize: 0.3,
          maxChildSize: 0.95,
          builder: (_, controller) => Container(
            decoration: const BoxDecoration(
              color: Color(0xFF0E0F12),
              borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
            ),
            padding: const EdgeInsets.all(16),
            child: Column(
              children: [
                Container(
                  width: 48,
                  height: 4,
                  decoration: BoxDecoration(
                    color: Colors.white12,
                    borderRadius: BorderRadius.circular(4),
                  ),
                ),
                const SizedBox(height: 12),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    IconButton(
                      onPressed: _prevMonth,
                      icon: const Icon(Icons.arrow_back_ios),
                      color: Colors.white,
                    ),
                    Text(
                      'Select Date',
                      style: GoogleFonts.playfairDisplay(
                        fontSize: 20,
                        color: Colors.white,
                      ),
                    ),
                    IconButton(
                      onPressed: _nextMonth,
                      icon: const Icon(Icons.arrow_forward_ios),
                      color: Colors.white,
                    ),
                  ],
                ),
                const SizedBox(height: 8),
                Text(
                  formatter.format(_viewDate),
                  style: const TextStyle(color: Colors.white70),
                ),
                const SizedBox(height: 8),
                Expanded(
                  child: GridView.builder(
                    controller: controller,
                    gridDelegate:
                        const SliverGridDelegateWithFixedCrossAxisCount(
                      crossAxisCount: 7,
                      childAspectRatio: 1.1,
                    ),
                    itemCount:
                        DateTime(_viewDate.year, _viewDate.month + 1, 0).day +
                            7, // simple grid including weekday headers
                    itemBuilder: (ctx, idx) {
                      // idx 0..6 show weekday short labels
                      if (idx < 7) {
                        final labels = [
                          'Su',
                          'Mo',
                          'Tu',
                          'We',
                          'Th',
                          'Fr',
                          'Sa',
                        ];
                        return Center(
                          child: Text(
                            labels[idx],
                            style: const TextStyle(
                              color: Colors.white70,
                              fontSize: 12,
                            ),
                          ),
                        );
                      }
                      final dayIndex = idx - 7 + 1;
                      final maxDay = DateTime(
                        _viewDate.year,
                        _viewDate.month + 1,
                        0,
                      ).day;
                      if (dayIndex > maxDay) return const SizedBox.shrink();
                      final dayDate = DateTime(
                        _viewDate.year,
                        _viewDate.month,
                        dayIndex,
                      );
                      final selected = _isMonthSelected(dayDate);
                      return GestureDetector(
                        onTap: () => _onDayTap(dayDate),
                        child: Container(
                          margin: const EdgeInsets.all(4),
                          decoration: BoxDecoration(
                            color:
                                selected ? primaryAccent : Colors.transparent,
                            shape: BoxShape.circle,
                          ),
                          child: Center(
                            child: Text(
                              '${dayDate.day}',
                              style: TextStyle(
                                color: selected ? Colors.white : Colors.white70,
                              ),
                            ),
                          ),
                        ),
                      );
                    },
                  ),
                ),
                Row(
                  children: [
                    Expanded(
                      child: ElevatedButton(
                        onPressed: () {
                          if (_firstSelected == null) {
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                content: Text('Pilih tanggal terlebih dahulu'),
                              ),
                            );
                            return;
                          }
                          final start = firstDayOfMonth(_firstSelected!);
                          final end = lastDayOfMonth(
                            _secondSelected ?? _firstSelected!,
                          );
                          final months = monthsBetween(
                            firstDayOfMonth(start),
                            firstDayOfMonth(end),
                          );
                          if (!_didReturn) {
                            _didReturn = true;
                            Navigator.of(context).pop(
                              MonthsSelection(
                                startDate: start,
                                endDate: end,
                                monthsCount: months,
                              ),
                            );
                          }
                        },
                        child: const Text('Select Guest'),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

const Color primaryAccent = Color(0xFF5D5CFF);
