// Auto-generated by Copilot per user prompt — manual review required
// child properties intentionally ordered for readability.
// ignore_for_file: sort_child_properties_last
import 'package:flutter/material.dart';

const _kSurface = Color(0xFF0E0F12);
const _kPrimary = Color(0xFF5D5CFF);

class PaymentSuccessPopup extends StatelessWidget {
  final VoidCallback onBackToHome;

  const PaymentSuccessPopup({super.key, required this.onBackToHome});

  @override
  Widget build(BuildContext context) {
    return Dialog(
      backgroundColor: Colors.transparent,
      child: Container(
        decoration: BoxDecoration(
          color: _kSurface,
          borderRadius: BorderRadius.circular(16),
        ),
        padding: const EdgeInsets.all(20),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            CircleAvatar(
              radius: 40,
              backgroundColor: _kPrimary,
              child: const Icon(Icons.check, color: Colors.white, size: 48),
            ),
            const SizedBox(height: 12),
            const Text(
              'Payment Success',
              style: TextStyle(color: Colors.white, fontSize: 18),
            ),
            const SizedBox(height: 8),
            const Text(
              'Your booking has been confirmed.',
              style: TextStyle(color: Colors.white70),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 16),
            ElevatedButton(
              onPressed: onBackToHome,
              style: ElevatedButton.styleFrom(backgroundColor: _kPrimary),
              child: const Text('Back to Home'),
            ),
          ],
        ),
      ),
    );
  }
}
