// Auto-generated by Copilot per user prompt — manual review required
import 'package:flutter/material.dart';

const _kSurface = Color(0xFF0E0F12);
const _kPrimary = Color(0xFF5D5CFF);

class PaymentQrisPlaceholder extends StatelessWidget {
  final String accountInfo;
  final VoidCallback onCopy;
  final VoidCallback onDone;

  const PaymentQrisPlaceholder({
    super.key,
    required this.accountInfo,
    required this.onCopy,
    required this.onDone,
  });

  @override
  Widget build(BuildContext context) {
    return Dialog(
      backgroundColor: Colors.transparent,
      insetPadding: const EdgeInsets.all(16),
      child: Container(
        decoration: BoxDecoration(
          color: _kSurface,
          borderRadius: BorderRadius.circular(16),
        ),
        padding: const EdgeInsets.all(16),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Placeholder QR
            Container(
              width: 220,
              height: 220,
              decoration: BoxDecoration(
                color: Colors.white12,
                borderRadius: BorderRadius.circular(12),
              ),
              child: Center(
                child: Text(
                  'QRIS\nPlaceholder',
                  textAlign: TextAlign.center,
                  style: const TextStyle(color: Colors.white30),
                ),
              ),
            ),
            const SizedBox(height: 12),
            Text(
              'Scan QRIS atau transfer ke rekening berikut',
              style: TextStyle(color: Colors.white70),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 8),
            SelectableText(
              accountInfo,
              style: const TextStyle(color: Colors.white),
            ),
            const SizedBox(height: 12),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                ElevatedButton.icon(
                  onPressed: onCopy,
                  icon: const Icon(Icons.copy),
                  label: const Text('Copy Account'),
                  style: ElevatedButton.styleFrom(backgroundColor: _kPrimary),
                ),
                TextButton(
                  onPressed: onDone,
                  child: const Text('Done (simulate success)'),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
