// Auto-generated by Copilot per user prompt — manual review required
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AddCardScreen extends StatefulWidget {
  const AddCardScreen({super.key});

  @override
  State<AddCardScreen> createState() => _AddCardScreenState();
}

class _AddCardScreenState extends State<AddCardScreen> {
  final _formKey = GlobalKey<FormState>();
  final _numberCtrl = TextEditingController();
  final _nameCtrl = TextEditingController();
  final _expiryCtrl = TextEditingController();
  final _cvvCtrl = TextEditingController();

  @override
  void dispose() {
    _numberCtrl.dispose();
    _nameCtrl.dispose();
    _expiryCtrl.dispose();
    _cvvCtrl.dispose();
    super.dispose();
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;
    final card = {
      'number': _numberCtrl.text.replaceAll(' ', ''),
      'name': _nameCtrl.text,
      'expiry': _expiryCtrl.text,
    };
    try {
      final sp = await SharedPreferences.getInstance();
      final raw = sp.getString('saved_cards');
      final list = raw == null ? <dynamic>[] : jsonDecode(raw) as List<dynamic>;
      list.add(card);
      await sp.setString('saved_cards', jsonEncode(list));
      // NOTE: For demo only we store card metadata in SharedPreferences.
      // In production you must tokenize card data and use a PCI-compliant flow
      // (do NOT store raw PAN/CVV). This app stores minimal card info for UX.
      debugPrint('Saved card metadata (masked) for user');
      if (!mounted) return;
      Navigator.of(context).pop(card);
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Gagal menyimpan kartu')));
    }
  }

  String _formatCardNumber(String s) {
    final digits = s.replaceAll(RegExp(r'\D'), '');
    final parts = <String>[];
    for (var i = 0; i < digits.length; i += 4) {
      parts.add(
        digits.substring(i, i + 4 > digits.length ? digits.length : i + 4),
      );
    }
    return parts.join(' ');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add Card'),
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      backgroundColor: const Color(0xFF0B0C10),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                controller: _numberCtrl,
                keyboardType: TextInputType.number,
                inputFormatters: [
                  FilteringTextInputFormatter.digitsOnly,
                  LengthLimitingTextInputFormatter(19),
                ],
                style: GoogleFonts.inter(color: Colors.white),
                decoration: const InputDecoration(
                  hintText: 'Card Number',
                  labelText: 'Card Number',
                ),
                onChanged: (v) =>
                    _numberCtrl.value = _numberCtrl.value.copyWith(
                      text: _formatCardNumber(v),
                      selection: TextSelection.collapsed(
                        offset: _formatCardNumber(v).length,
                      ),
                    ),
                validator: (v) {
                  final d = v?.replaceAll(' ', '') ?? '';
                  if (d.length < 16) return 'Card number must be 16 digits';
                  return null;
                },
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _nameCtrl,
                style: GoogleFonts.inter(color: Colors.white),
                decoration: const InputDecoration(
                  hintText: 'Card Holder Name',
                  labelText: 'Name',
                ),
                validator: (v) =>
                    (v == null || v.isEmpty) ? 'Name required' : null,
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _expiryCtrl,
                      style: GoogleFonts.inter(color: Colors.white),
                      decoration: const InputDecoration(
                        hintText: 'MM/YY',
                        labelText: 'Expiry',
                      ),
                      validator: (v) {
                        if (v == null || v.isEmpty) return 'Expiry required';
                        final parts = v.split('/');
                        if (parts.length != 2) return 'Invalid';
                        final mm = int.tryParse(parts[0]);
                        final yy = int.tryParse(parts[1]);
                        if (mm == null || yy == null) return 'Invalid';
                        if (mm < 1 || mm > 12) return 'Invalid';
                        final exp = DateTime(2000 + yy, mm + 1, 0);
                        if (exp.isBefore(DateTime.now())) return 'Card expired';
                        return null;
                      },
                    ),
                  ),
                  const SizedBox(width: 12),
                  SizedBox(
                    width: 100,
                    child: TextFormField(
                      controller: _cvvCtrl,
                      obscureText: true,
                      keyboardType: TextInputType.number,
                      inputFormatters: [
                        FilteringTextInputFormatter.digitsOnly,
                        LengthLimitingTextInputFormatter(3),
                      ],
                      style: GoogleFonts.inter(color: Colors.white),
                      decoration: const InputDecoration(
                        hintText: 'CVV',
                        labelText: 'CVV',
                      ),
                      validator: (v) {
                        if (v == null || v.length != 3) return 'Invalid CVV';
                        return null;
                      },
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 24),
              SizedBox(
                width: double.infinity,
                height: 48,
                child: ElevatedButton(
                  onPressed: _save,
                  child: const Text('Save Card'),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
