// Auto-generated by Copilot per user prompt — review required

int inclusiveMonthsCount(DateTime a, DateTime b) {
  final start = DateTime(a.year, a.month);
  final end = DateTime(b.year, b.month);
  final yearDiff = end.year - start.year;
  final monthDiff = end.month - start.month;
  return yearDiff * 12 + monthDiff + 1;
}

int applyGuestSurcharge(int subtotal, int totalGuests) {
  if (totalGuests >= 5) return subtotal * 2;
  if (totalGuests == 4) return subtotal + 50000;
  return subtotal;
}

int calculateGrandTotal({
  required int monthlyPrice,
  required int months,
  required int totalGuests,
  int discount = 0,
  int fees = 0,
}) {
  final base = monthlyPrice * months;
  final afterGuest = applyGuestSurcharge(base, totalGuests);
  final subtotal = afterGuest - discount;
  return subtotal + fees;
}
