// Auto-generated by Copilot per user prompt — review required
import 'dart:async';

import 'package:flutter/widgets.dart';

class NavigationHelper {
  // last navigation timestamp used to prevent double navigation
  static DateTime? _lastNav;
  static const _minInterval = Duration(milliseconds: 300);

  static bool _tooSoon() {
    final now = DateTime.now();
    if (_lastNav == null) {
      _lastNav = now;
      return false;
    }
    final diff = now.difference(_lastNav!);
    if (diff < _minInterval) return true;
    _lastNav = now;
    return false;
  }

  static Future<void> safePush(
    BuildContext context,
    String routeName, {
    Object? args,
  }) async {
    if (_tooSoon()) return;
    if (!Navigator.of(context).mounted) return;
    await Navigator.of(context).pushNamed(routeName, arguments: args);
  }

  static Future<T?> safePushResult<T>(
    BuildContext context,
    String routeName, {
    Object? args,
  }) async {
    if (_tooSoon()) return null;
    if (!Navigator.of(context).mounted) return null;
    return Navigator.of(context).pushNamed<T>(routeName, arguments: args);
  }
}
